general:
  - flags: [-h, --help]
    action: help
    help: "• Show this help message and exit"

  - flags: [-v, --version]
    action: version
    version: JTrader v1.0
    help: "• Show program version number and exit"
  
  - flags: [-s, --snapshot]
    metavar: "Coin"
    nargs: 2
    help: "• Specify two currencies to find most profitable path between"


commands:
  start:
    help: "• Start a trading process"
    func: start
    args:
      - flags: [-c, --capital]
        default: 1000
        help: • Select starting capital amount (USD)

      - flags: [-f, --frequency]
        default: 1
        help: • Number of times/minute to check for arbitrage
  stop:
    help: "• Stops the trading process"
    func: stop
    args: []
